dist: trusty
language: java
jdk:
- oraclejdk8
install:
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins -B
script:
- mvn clean install -B
cache:
  directories:
  - $HOME/.m2
